export const MOVIE_SEARCH_REQUEST = 'MOVIE_SEARCH_REQUEST';
export const MOVIE_SEARCH_SUCCESS = 'MOVIE_SEARCH_SUCCESS';
export const MOVIE_SEARCH_FAIL = 'MOVIE_SEARCH_FAIL';

export const MOVIE_NOWPLAYING_REQUEST = 'MOVIE_NOWPLAYING_REQUEST';
export const MOVIE_NOWPLAYING_SUCCESS = 'MOVIE_NOWPLAYING_SUCCESS';
export const MOVIE_NOWPLAYING_FAIL = 'MOVIE_NOWPLAYING_FAIL';

export const MOVIE_POPULAR_REQUEST = 'MOVIE_POPULAR_REQUEST';
export const MOVIE_POPULAR_SUCCESS = 'MOVIE_POPULAR_SUCCESS';
export const MOVIE_POPULAR_FAIL = 'MOVIE_POPULAR_FAIL';

export const MOVIE_TOPRATED_REQUEST = 'MOVIE_TOPRATED_REQUEST';
export const MOVIE_TOPRATED_SUCCESS = 'MOVIE_TOPRATED_SUCCESS';
export const MOVIE_TOPRATED_FAIL = 'MOVIE_TOPRATED_FAIL';

export const MOVIE_UPCOMING_REQUEST = 'MOVIE_UPCOMING_REQUEST';
export const MOVIE_UPCOMING_SUCCESS = 'MOVIE_UPCOMING_SUCCESS';
export const MOVIE_UPCOMING_FAIL = 'MOVIE_UPCOMING_FAIL';

export const MOVIE_LATEST_REQUEST = 'MOVIE_LATEST_REQUEST';
export const MOVIE_LATEST_SUCCESS = 'MOVIE_LATEST_SUCCESS';
export const MOVIE_LATEST_FAIL = 'MOVIE_LATEST_FAIL';

export const MOVIE_DETAIL_REQUEST = 'MOVIE_DETAIL_REQUEST';
export const MOVIE_DETAIL_SUCCESS = 'MOVIE_DETAIL_SUCCESS';
export const MOVIE_DETAIL_FAIL = 'MOVIE_DETAIL_FAIL';

export const MOVIE_VIDEO_REQUEST = 'MOVIE_VIDEO_REQUEST';
export const MOVIE_VIDEO_SUCCESS = 'MOVIE_VIDEO_SUCCESS';
export const MOVIE_VIDEO_FAIL = 'MOVIE_VIDEO_FAIL';

export const MOVIE_CASTS_REQUEST = 'MOVIE_CASTS_REQUEST';
export const MOVIE_CASTS_SUCCESS = 'MOVIE_CASTS_SUCCESS';
export const MOVIE_CASTS_FAIL = 'MOVIE_CASTS_FAIL';

export const MOVIE_SIMILAR_REQUEST = 'MOVIE_SIMILAR_REQUEST';
export const MOVIE_SIMILAR_SUCCESS = 'MOVIE_SIMILAR_SUCCESS';
export const MOVIE_SIMILAR_FAIL = 'MOVIE_SIMILAR_FAIL';

export const ADD_MOVIE_TO_FAVORITE = 'ADD_MOVIE_TO_FAVORITE';


