export const MOVIE_SEARCH_REQUEST = 'MOVIE_SEARCH_REQUEST';
export const MOVIE_SEARCH_SUCCESS = 'MOVIE_SEARCH_SUCCESS';
export const MOVIE_SEARCH_FAIL = 'MOVIE_SEARCH_FAIL';

export const MOVIE_NOWPLAYING_REQUEST = 'MOVIE_NOWPLAYING_REQUEST';
export const MOVIE_NOWPLAYING_SUCCESS = 'MOVIE_NOWPLAYING_SUCCESS';
export const MOVIE_NOWPLAYING_FAIL = 'MOVIE_NOWPLAYING_FAIL';

export const MOVIE_POPULAR_REQUEST = 'MOVIE_POPULAR_REQUEST';
export const MOVIE_POPULAR__SUCCESS = 'MOVIE_POPULAR__SUCCESS';
export const MOVIE_POPULAR__FAIL = 'MOVIE_POPULAR__FAIL';

export const MOVIE_TOPRATED_REQUEST = 'MOVIE_TOPRATED_REQUEST';
export const MOVIE_TOPRATED__SUCCESS = 'MOVIE_TOPRATED__SUCCESS';
export const MOVIE_TOPRATED__FAIL = 'MOVIE_TOPRATED__FAIL';

export const MOVIE_LATEST_REQUEST = 'MOVIE_LATEST_REQUEST';
export const MOVIE_LATEST__SUCCESS = 'MOVIE_LATEST__SUCCESS';
export const MOVIE_LATEST__FAIL = 'MOVIE_LATEST__FAIL';

export const MOVIE_DETAIL_REQUEST = 'MOVIE_DETAIL_REQUEST';
export const MOVIE_DETAIL__SUCCESS = 'MOVIE_DETAIL__SUCCESS';
export const MOVIE_DETAIL__FAIL = 'MOVIE_DETAIL__FAIL';



