export const PERSON_SEARCH_REQUEST = 'PERSON_SEARCH_REQUEST';
export const PERSON_SEARCH_SUCCESS = 'PERSON_SEARCH_SUCCESS';
export const PERSON_SEARCH_FAIL = 'PERSON_SEARCH_FAIL';

export const PERSON_DETAIL_REQUEST = 'PERSON_DETAIL_REQUEST';
export const PERSON_DETAIL_SUCCESS = 'PERSON_DETAIL_SUCCESS';
export const PERSON_DETAIL_FAIL = 'PERSON_DETAIL_FAIL';

export const PERSON_CREDITS_REQUEST = 'PERSON_CREDITS_REQUEST';
export const PERSON_CREDITS_SUCCESS = 'PERSON_CREDITS_SUCCESS';
export const PERSON_CREDITS_FAIL = 'PERSON_CREDITS_FAIL';



